/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mypaint.gui;

import java.awt.Color;
import java.awt.event.MouseEvent;
import javax.swing.JColorChooser;


/**
 *
 * @author otonr
 */
public class MainFrame extends javax.swing.JFrame {
    private int xPress;
    private int yPress;
    
    /**
     * Creates new form Frame
     */
    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupDraw = new javax.swing.ButtonGroup();
        panelTools = new javax.swing.JPanel();
        btnLine = new javax.swing.JToggleButton();
        btnRectangle = new javax.swing.JToggleButton();
        btnEllipse = new javax.swing.JToggleButton();
        btnColorContour = new javax.swing.JButton();
        checkColorlessContour = new javax.swing.JCheckBox();
        btnColorFill = new javax.swing.JButton();
        checkColorlessFill = new javax.swing.JCheckBox();
        CheckBox1 = new mypaint.gui.DrawPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyPaint");
        setResizable(false);

        btnGroupDraw.add(btnLine);
        btnLine.setText("Line");

        btnGroupDraw.add(btnRectangle);
        btnRectangle.setText("Rectangle");
        btnRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRectangleActionPerformed(evt);
            }
        });

        btnGroupDraw.add(btnEllipse);
        btnEllipse.setText("Ellipse");

        btnColorContour.setForeground(new java.awt.Color(0, 0, 0));
        btnColorContour.setText("\u25A1");
        btnColorContour.setToolTipText("Contour Color");
        btnColorContour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorContourActionPerformed(evt);
            }
        });

        checkColorlessContour.setText("Colorless");

        btnColorFill.setForeground(new java.awt.Color(255, 255, 255));
        btnColorFill.setText("\u25A0");
        btnColorFill.setToolTipText("Fill Color");
        btnColorFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnColorFillActionPerformed(evt);
            }
        });

        checkColorlessFill.setText("Colorless");

        javax.swing.GroupLayout panelToolsLayout = new javax.swing.GroupLayout(panelTools);
        panelTools.setLayout(panelToolsLayout);
        panelToolsLayout.setHorizontalGroup(
            panelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelToolsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnLine, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRectangle, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEllipse, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(btnColorContour)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkColorlessContour, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnColorFill)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkColorlessFill, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        panelToolsLayout.setVerticalGroup(
            panelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelToolsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnColorContour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelToolsLayout.createSequentialGroup()
                        .addGroup(panelToolsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnLine)
                            .addComponent(btnRectangle)
                            .addComponent(btnEllipse)
                            .addComponent(checkColorlessContour)
                            .addComponent(btnColorFill)
                            .addComponent(checkColorlessFill))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        CheckBox1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                CheckBox1MouseDragged(evt);
            }
        });
        CheckBox1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                CheckBox1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                CheckBox1MouseReleased(evt);
            }
        });

        javax.swing.GroupLayout CheckBox1Layout = new javax.swing.GroupLayout(CheckBox1);
        CheckBox1.setLayout(CheckBox1Layout);
        CheckBox1Layout.setHorizontalGroup(
            CheckBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        CheckBox1Layout.setVerticalGroup(
            CheckBox1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelTools, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTools, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CheckBox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CheckBox1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox1MousePressed
        xPress = evt.getX();
        yPress = evt.getY();
    }//GEN-LAST:event_CheckBox1MousePressed

    private void CheckBox1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox1MouseReleased
        GeometricShapes newGeometricShapes = newGeometricShapes(evt);

        CheckBox1.setTempShapes(null);
        CheckBox1.addGeometricShapes(newGeometricShapes);
        CheckBox1.repaint();
    }//GEN-LAST:event_CheckBox1MouseReleased

    private void CheckBox1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CheckBox1MouseDragged

        GeometricShapes newTempShapes = newGeometricShapes(evt);
        
        CheckBox1.setTempShapes(newTempShapes);
        CheckBox1.repaint();
     
    }//GEN-LAST:event_CheckBox1MouseDragged

    private void btnRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRectangleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRectangleActionPerformed

    private void btnColorContourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorContourActionPerformed
        Color c = JColorChooser.showDialog(
                this,
                "Color Contour",
                btnColorContour.getForeground());
        
        if (c != null){
            btnColorContour.setForeground(c);
        }
    }//GEN-LAST:event_btnColorContourActionPerformed

    private void btnColorFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnColorFillActionPerformed
        Color c = JColorChooser.showDialog(
                this,
                "Color Fill",
                btnColorFill.getForeground());
        
        if (c != null){
            btnColorFill.setForeground(c);
        }
    }//GEN-LAST:event_btnColorFillActionPerformed
    
    private GeometricShapes newGeometricShapes(MouseEvent evt ){
        GeometricShapes newGeometricShapes = null;
        
        if (btnLine.isSelected())newGeometricShapes = new Line();
        else if (btnRectangle.isSelected())newGeometricShapes = new Rectangle();
        else if (btnEllipse.isSelected())newGeometricShapes = new Ellipse();
        
        newGeometricShapes.setxInitial(xPress);
        newGeometricShapes.setyInitial(yPress);
        newGeometricShapes.setxEnd(evt.getX());
        newGeometricShapes.setyEnd(evt.getY());
        
        if (checkColorlessContour.isSelected()){
            newGeometricShapes.setColorContour(null);
        } else {
            newGeometricShapes.setColorContour(btnColorContour.getForeground());
        }
        if (checkColorlessFill.isSelected()){
            newGeometricShapes.setColorFill(null);
        } else {
            newGeometricShapes.setColorFill(btnColorFill.getForeground());
        }
        
        return newGeometricShapes;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private mypaint.gui.DrawPanel CheckBox1;
    private javax.swing.JButton btnColorContour;
    private javax.swing.JButton btnColorFill;
    private javax.swing.JToggleButton btnEllipse;
    private javax.swing.ButtonGroup btnGroupDraw;
    private javax.swing.JToggleButton btnLine;
    private javax.swing.JToggleButton btnRectangle;
    private javax.swing.JCheckBox checkColorlessContour;
    private javax.swing.JCheckBox checkColorlessFill;
    private javax.swing.JPanel panelTools;
    // End of variables declaration//GEN-END:variables
}
